<script src="<?= $default; ?>js/iconify-icon.min.js"></script>
<script src="<?= $default; ?>js/jquery-1.11.0.min.js"></script> 
<script src="<?= $default; ?>js/bootstrap.min.js"></script> 
<script src="<?= $default; ?>js/own-menu.js"></script> 
<script src="<?= $default; ?>js/owl.carousel.min.js"></script> 
<script src="<?= $default; ?>js/jquery.superslides.js"></script> 
<script src="<?= $default; ?>js/masonry.pkgd.min.js"></script> 
<script src="<?= $default; ?>js/jquery.stellar.min.js"></script> 
<script src="<?= $default; ?>js/jquery-ui-1.10.3.custom.js"></script> 
<script src="<?= $default; ?>js/jquery.magnific-popup.min.js"></script> 
<script src="<?= $default; ?>js/jquery.isotope.min.js"></script> 
<script src="<?= $default; ?>js/jquery.flexslider-min.js"></script> 
<script src="<?= $default; ?>js/appointment.js"></script> 
<script src="<?= $default; ?>js/jquery.downCount.js"></script> 
<script src="<?= $default; ?>js/counter.js"></script> 
<script src="<?= $default; ?>js/main.js"></script>